baseURL = "https://brnr.link/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Burner's links"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[social]
twitter = "BurnerWah"

[author]
name = "Burner"
headline = "Smol wah"
image = "img/pfp.webp"

links = [
    { github = { href = "https://github.com/BurnerWah", text = "GitHub / @BurnerWah" } },
    { mastodon = { href = "https://queer.party/@burner", text = "Mastodon / @burner@queer.party" } },
    { mastodon = { href = "https://stop.voring.me/@burner", text = "Misskey / @burner@stop.voring.me" } },
    # { link = { href = "https://burner.gay/", text = "Website" } },
    { cohost = { href = "https://cohost.org/burner", text = "cohost / @burner" } },
    { link = { href = "https://furry.codes/", text = "Blog" } },
    { discord = { href = "https://discord.com/users/335251371701829632", text = "Discord / Burner#5817" } },
    { telegram = { href = "https://t.me/BurnerWah", text = "Telegram / @BurnerWah" } },
    { twitch = { href = "https://www.twitch.tv/burnerstwitch", text = "Twitch / @BurnersTwitch" } },
    { steam = { href = "https://steamcommunity.com/id/BurnerWah", text = "Steam / @BurnerWah" } },
    { pronouns-page = { href = "https://en.pronouns.page/@Burner", text = "en.pronouns.page / @Burner" } },
    # { twitter = { href = "https://twitter.com/BurnerWah", text = "Twitter / @BurnerWah" } },
    { tumblr = { href = "https://www.tumblr.com/burnerwah", text = "Tumblr / @burnerwah" } },
    { youtube = { href = "https://www.youtube.com/@BurnerWah", text = "YouTube / @BurnerWah" } },
    { gitlab = { href = "https://gitlab.com/BurnerWah", text = "GitLab / @BurnerWah" } },
    { codeberg = { href = "https://codeberg.org/BurnerWah", text = "Codeberg / @BurnerWah" } },
    # { keybase = { href = "https://keybase.io/yaboiburner", text = "Keybase / @yaboiburner" } },
    # { email = "mailto:burner@burner.gay" },
    # { lastfm = "https://www.last.fm/user/YaBoiBurner" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { whatsapp = "https://wa.me/phone-number" },
]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
